// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Services.HouseDBApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CurrentP1Item
    {
        /// <summary>
        /// Initializes a new instance of the CurrentP1Item class.
        /// </summary>
        public CurrentP1Item()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CurrentP1Item class.
        /// </summary>
        public CurrentP1Item(string name = default(string), double? value = default(double?))
        {
            Name = name;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public double? Value { get; set; }

    }
}
