// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Services.HouseDBApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class FitbitActivityStep
    {
        /// <summary>
        /// Initializes a new instance of the FitbitActivityStep class.
        /// </summary>
        public FitbitActivityStep()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FitbitActivityStep class.
        /// </summary>
        public FitbitActivityStep(int? steps = default(int?), System.DateTime? date = default(System.DateTime?), long? id = default(long?))
        {
            Steps = steps;
            Date = date;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "steps")]
        public int? Steps { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

    }
}
