// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Services.HouseDBApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class FitbitWeekOverviewReponse
    {
        /// <summary>
        /// Initializes a new instance of the FitbitWeekOverviewReponse class.
        /// </summary>
        public FitbitWeekOverviewReponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the FitbitWeekOverviewReponse class.
        /// </summary>
        public FitbitWeekOverviewReponse(IList<FitbitWeekOverviewItem> fitbitWeekOverviewItems = default(IList<FitbitWeekOverviewItem>))
        {
            FitbitWeekOverviewItems = fitbitWeekOverviewItems;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fitbitWeekOverviewItems")]
        public IList<FitbitWeekOverviewItem> FitbitWeekOverviewItems { get; set; }

    }
}
