// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Services.HouseDBApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class InsertCallbackClientModel
    {
        /// <summary>
        /// Initializes a new instance of the InsertCallbackClientModel class.
        /// </summary>
        public InsertCallbackClientModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the InsertCallbackClientModel class.
        /// </summary>
        public InsertCallbackClientModel(string authCode = default(string), string clientId = default(string))
        {
            AuthCode = authCode;
            ClientId = clientId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "authCode")]
        public string AuthCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "clientId")]
        public string ClientId { get; set; }

    }
}
