// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Services.HouseDBApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class KwhMonthUsageValue
    {
        /// <summary>
        /// Initializes a new instance of the KwhMonthUsageValue class.
        /// </summary>
        public KwhMonthUsageValue()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KwhMonthUsageValue class.
        /// </summary>
        public KwhMonthUsageValue(int? month = default(int?), double? usage = default(double?), string monthString = default(string))
        {
            Month = month;
            Usage = usage;
            MonthString = monthString;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "month")]
        public int? Month { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usage")]
        public double? Usage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "monthString")]
        public string MonthString { get; private set; }

    }
}
