// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Services.HouseDBApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class LastMotionDetectionsClientModel
    {
        /// <summary>
        /// Initializes a new instance of the LastMotionDetectionsClientModel
        /// class.
        /// </summary>
        public LastMotionDetectionsClientModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LastMotionDetectionsClientModel
        /// class.
        /// </summary>
        public LastMotionDetectionsClientModel(IList<LastMotionDetectionDetail> lastMotionDetectionDetails = default(IList<LastMotionDetectionDetail>), ElapsedTime elapsedTime = default(ElapsedTime))
        {
            LastMotionDetectionDetails = lastMotionDetectionDetails;
            ElapsedTime = elapsedTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastMotionDetectionDetails")]
        public IList<LastMotionDetectionDetail> LastMotionDetectionDetails { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elapsedTime")]
        public ElapsedTime ElapsedTime { get; set; }

    }
}
