// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Services.HouseDBApi.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class P1OverviewClientModel
    {
        /// <summary>
        /// Initializes a new instance of the P1OverviewClientModel class.
        /// </summary>
        public P1OverviewClientModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the P1OverviewClientModel class.
        /// </summary>
        public P1OverviewClientModel(IList<CurrentP1Item> items = default(IList<CurrentP1Item>), ElapsedTime elapsedTime = default(ElapsedTime))
        {
            Items = items;
            ElapsedTime = elapsedTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<CurrentP1Item> Items { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elapsedTime")]
        public ElapsedTime ElapsedTime { get; set; }

    }
}
