// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Services.HouseDBApi.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class P1WeekUsage
    {
        /// <summary>
        /// Initializes a new instance of the P1WeekUsage class.
        /// </summary>
        public P1WeekUsage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the P1WeekUsage class.
        /// </summary>
        public P1WeekUsage(int? week = default(int?), double? p1Usage = default(double?), string displayText = default(string))
        {
            Week = week;
            P1Usage = p1Usage;
            DisplayText = displayText;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "week")]
        public int? Week { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "p1Usage")]
        public double? P1Usage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayText")]
        public string DisplayText { get; set; }

    }
}
