// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Services.Api.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SevenSegmentClientModel
    {
        /// <summary>
        /// Initializes a new instance of the SevenSegmentClientModel class.
        /// </summary>
        public SevenSegmentClientModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SevenSegmentClientModel class.
        /// </summary>
        public SevenSegmentClientModel(int? watt = default(int?), double? today = default(double?), double? thisWeek = default(double?), double? thisMonth = default(double?), double? lastMonth = default(double?), ElapsedTime elapsedTime = default(ElapsedTime))
        {
            Watt = watt;
            Today = today;
            ThisWeek = thisWeek;
            ThisMonth = thisMonth;
            LastMonth = lastMonth;
            ElapsedTime = elapsedTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "watt")]
        public int? Watt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "today")]
        public double? Today { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "thisWeek")]
        public double? ThisWeek { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "thisMonth")]
        public double? ThisMonth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastMonth")]
        public double? LastMonth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elapsedTime")]
        public ElapsedTime ElapsedTime { get; set; }

    }
}
