# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(Build.SourcesDirectory)/HouseDB.Api'
    arguments: '--configuration $(buildConfiguration) --runtime linux-x64 --output $(Build.SourcesDirectory)/publish --self-contained'
    zipAfterPublish: false
    modifyOutputPath: false
    feedsToUse: 'select'
    versioningScheme: 'off'
# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#     projects: '**/*Tests/*.csproj'
#     arguments: '--configuration $(buildConfiguration)'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/publish'
    archiveFile: '$(Build.ArtifactStagingDirectory)/deploy-publish$(Build.BuildId).zip'
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'azurebuild.inexpro.nl'
    sourceFolder: '$(Build.ArtifactStagingDirectory)'
    contents: '**'
    targetFolder: '/home/azurebuild/housedb-deploy/$(Build.BuildId)/'