// <auto-generated />
using System;
using HouseDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HouseDB.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200316111319_P1Consumption")]
    partial class P1Consumption
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HouseDB.Core.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DataMineChannel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("DeletedByIdentityServerUserId")
                        .HasColumnType("int");

                    b.Property<int>("DomoticzKwhIdx")
                        .HasColumnType("int");

                    b.Property<int>("DomoticzMotionDetectionIdx")
                        .HasColumnType("int");

                    b.Property<int>("DomoticzWattIdx")
                        .HasColumnType("int");

                    b.Property<bool>("IsForKwhImport")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsForTemperatureImport")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("VeraChannel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("HouseDB.Core.Entities.P1Consumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateTimeDeleted")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("DayUsage")
                        .HasColumnType("double");

                    b.Property<int?>("DeletedByIdentityServerUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("P1Consumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
