// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Exporter.HouseDBService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class KwhDateUsage
    {
        /// <summary>
        /// Initializes a new instance of the KwhDateUsage class.
        /// </summary>
        public KwhDateUsage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KwhDateUsage class.
        /// </summary>
        public KwhDateUsage(System.DateTime? date = default(System.DateTime?), double? usage = default(double?), long? deviceID = default(long?), long? id = default(long?))
        {
            Date = date;
            Usage = usage;
            DeviceID = deviceID;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "date")]
        public System.DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usage")]
        public double? Usage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceID")]
        public long? DeviceID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

    }
}
