// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Exporter.HouseDBService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class KwhWeekUsageValue
    {
        /// <summary>
        /// Initializes a new instance of the KwhWeekUsageValue class.
        /// </summary>
        public KwhWeekUsageValue()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KwhWeekUsageValue class.
        /// </summary>
        public KwhWeekUsageValue(int? week = default(int?), double? usage = default(double?))
        {
            Week = week;
            Usage = usage;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "week")]
        public int? Week { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "usage")]
        public double? Usage { get; set; }

    }
}
