// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace HouseDB.Exporter.HouseDBService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SevenSegmentClientModel
    {
        /// <summary>
        /// Initializes a new instance of the SevenSegmentClientModel class.
        /// </summary>
        public SevenSegmentClientModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SevenSegmentClientModel class.
        /// </summary>
        public SevenSegmentClientModel(string watt = default(string), string lastWeekTotal = default(string), string thisWeekTotal = default(string), string lastMonthTotal = default(string), string thisMonthTotal = default(string), ElapsedTime elapsedTime = default(ElapsedTime))
        {
            Watt = watt;
            LastWeekTotal = lastWeekTotal;
            ThisWeekTotal = thisWeekTotal;
            LastMonthTotal = lastMonthTotal;
            ThisMonthTotal = thisMonthTotal;
            ElapsedTime = elapsedTime;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "watt")]
        public string Watt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastWeekTotal")]
        public string LastWeekTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "thisWeekTotal")]
        public string ThisWeekTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lastMonthTotal")]
        public string LastMonthTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "thisMonthTotal")]
        public string ThisMonthTotal { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "elapsedTime")]
        public ElapsedTime ElapsedTime { get; set; }

    }
}
