// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Proxy.HouseDBService.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CurrentUsagesClientModel
    {
        /// <summary>
        /// Initializes a new instance of the CurrentUsagesClientModel class.
        /// </summary>
        public CurrentUsagesClientModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CurrentUsagesClientModel class.
        /// </summary>
        public CurrentUsagesClientModel(IList<CurrentUsage> currentUsages = default(IList<CurrentUsage>))
        {
            CurrentUsages = currentUsages;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "currentUsages")]
        public IList<CurrentUsage> CurrentUsages { get; set; }

    }
}
