// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Proxy.HouseDBService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ElapsedTime
    {
        /// <summary>
        /// Initializes a new instance of the ElapsedTime class.
        /// </summary>
        public ElapsedTime()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ElapsedTime class.
        /// </summary>
        public ElapsedTime(long? milliseconds = default(long?), int? seconds = default(int?))
        {
            Milliseconds = milliseconds;
            Seconds = seconds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "milliseconds")]
        public long? Milliseconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "seconds")]
        public int? Seconds { get; set; }

    }
}
