// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Proxy.HouseDBService.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PostGetMotionDetections
    {
        /// <summary>
        /// Initializes a new instance of the PostGetMotionDetections class.
        /// </summary>
        public PostGetMotionDetections()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostGetMotionDetections class.
        /// </summary>
        public PostGetMotionDetections(int? week = default(int?), int? deviceID = default(int?))
        {
            Week = week;
            DeviceID = deviceID;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "week")]
        public int? Week { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceID")]
        public int? DeviceID { get; set; }

    }
}
